Pentagon
Losssaw3/NewRepository pull request #1
Opened 2023-04-24 07:23 UTC by Losssaw3

Класс Пентагон и точка

2023-04-24 17:16 UTC, MarinaPaley requested changes
1. Нет файлов проектов и решения (ничего не могу проверить)
2. Немножко)

2023-04-24 17:16 UTC, MarinaPaley commented on FIgure/Pentagon/Pentagon.cpp
> +		throw std::out_of_range("����� �� ����� ���� �������������!");
Файл должен быть сохранен в кодировке `UTF-8`

2023-04-24 17:16 UTC, MarinaPaley commented on FIgure/Pentagon/Pentagon.cpp
> +		perimeter += (distance(pentagonPoints[i], pentagonPoints[i + 1]));
А может в конструкторе сразу определить длину стороны и хранить ее. Фигура же правильная, периметр будет рассчитываться проще.

А теперь внимательно проверяю дальше. Так сторона же есть, зачем так сложно находить периметр?

2023-04-24 17:16 UTC, MarinaPaley commented on FIgure/Pentagon/Pentagon.cpp
> +	return pentagonString;
```cpp
stringstream buffer;
for (auto point& : pentagonPoints)
	{
		buffer << point.to_string();
	}

return buffer.str();
```

2023-04-24 17:16 UTC, MarinaPaley commented on FIgure/Pentagon/Pentagon.h
> +		Pentagon(const double edge = 10, const Point centre = { 0, 0 });
Уберите значения по умолчанию, не нужно.

2023-04-24 17:16 UTC, MarinaPaley commented on FIgure/Pentagon/Point.cpp
> +	return pointString;
Для того, чтобы не показывать много знаков после запятой, можно посмотреть в сторону `setpresicion` в `ionmanip`
```cpp
stringstream buffer;
buffer << this-> abcissa << ', ' << this->ordinate;
return buffer.str();
```

Этот метод, вообще, должен быть статический 😄

2023-04-24 18:41 UTC, Losssaw3 commented on FIgure/Pentagon/Pentagon.h
> +		Pentagon(const double edge = 10, const Point centre = { 0, 0 });
тогда без конструктора по умолчанию получается?

2023-04-24 18:41 UTC, Losssaw3 commented on FIgure/Pentagon/Point.cpp
> +	return pointString;
уже не показывает само решилось как-то)

2023-04-25 17:27 UTC, MarinaPaley requested changes
Я все же не понимаю, как запустить Вашу программу
![image](https://user-images.githubusercontent.com/26978698/234355376-a5c123c4-ab1f-4569-b27e-c678e767d079.png)

2023-04-25 17:27 UTC, MarinaPaley commented on FIgure/Pentagon/Pentagon.h
> +		Pentagon(const double edge = 10, const Point centre = { 0, 0 });
Да

2023-04-25 17:27 UTC, MarinaPaley commented on FIgure/Pentagon/Pentagon.h
> +		double distance(Point first, Point second);
Получается, что метод и не нужен

2023-04-25 17:27 UTC, MarinaPaley commented on FIgure/Pentagon/Pentagon.h
> +		std::string ToString();
Точно не нужен.

2023-04-25 17:27 UTC, MarinaPaley commented on FIgure/Pentagon/Pentagon.cpp
> +		buffer << point.to_string();
`buffer << point;`

2023-04-25 17:27 UTC, MarinaPaley commented on FIgure/Pentagon/Pentagon.cpp
> +	for (std::vector<Point>::const_iterator out_it = pentagon.pentagonPoints.cbegin(); out_it < pentagon.pentagonPoints.cend() - 1; ++out_it)
Что это?
[ostream_iterator](https://cplusplus.com/reference/iterator/ostream_iterator/)
```cpp
```

``` / ostream_iterator example
#include <iostream>     // std::cout
#include <iterator>     // std::ostream_iterator
#include <vector>       // std::vector
#include <algorithm>    // std::copy

int main () {
  std::vector<int> myvector;
  for (int i=1; i<10; ++i) myvector.push_back(i*10);

  std::ostream_iterator<int> out_it (std::cout,", ");
  std::copy ( myvector.begin(), myvector.end(), out_it );
  return 0;
}
```

2023-04-25 17:27 UTC, MarinaPaley commented on FIgure/Pentagon/Point.cpp
> +std::ostream& PointClass::operator<<(std::ostream& out, const Point& point)
Нужен или оператора сдвига, или метод `to_string`.
В задании было "Определить статический метод сериализации в строку ToString() и то, если Вы используете тесты `NUnit`".

2023-05-01 18:03 UTC, merged